# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      displayName: Install Node.js 14.18.1
      inputs:
        versionSpec: 14.18.1

    - task: CmdLine@2
      displayName: Install Dependencies
      inputs:
        script: npm install -g mbt @ui5/cli

    - task: CmdLine@2
      displayName: Build
      inputs:
        script: mbt build -p=cf -s=$(Agent.BuildDirectory)/s

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        path: $(Agent.BuildDirectory)/s/mta_archives/project_planning_1.0.1.mtar
        artifactName: ProjectPlanningMTA
